### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by kiquenet** [hugorodgerbrown/HipChat.net#23]
Suggestion: working together https://github.com/KyleGobel/Hipchat-CS ?

**Comment by hugorodgerbrown** [comment]
Hi @kiquenet - I'm the author of the project, and I left .NET behind many years ago - so my point of view the project is certainly 'mothballed' - I don't have a Windows machine, an IDE or tbh the .NET skills to maintain it any longer. I did hand over ownership of it a couple of years ago (on nuget) so if you don't hear anything back from anyone else (I can't remember to whom I gave control) then consider it dead - or at least in stasis.
